### ISSUE TITLE
Cu/Pd option

### ISSUE THREAD

**Issue by awvwgk** [grimme-lab/cefine#1]
@fabothch @haneug since you recently encounter problems with Cu/Pd containing systems, this might be the cause. There is a special `strange_elem` option which might add one line to much and drop the charge here:
https://github.com/grimme-lab/cefine/blob/061470c4b76138110bce429045b8c96b930b6008/cefine.f90#L870-L875

It is set here by a call to the `atoms` routine:
https://github.com/grimme-lab/cefine/blob/061470c4b76138110bce429045b8c96b930b6008/cefine.f90#L768-L769

Defined here as logical `cu_pd`:
https://github.com/grimme-lab/cefine/blob/061470c4b76138110bce429045b8c96b930b6008/cefine.f90#L1415

Which only sets this flag for Cu/Pd containing systems:
https://github.com/grimme-lab/cefine/blob/061470c4b76138110bce429045b8c96b930b6008/cefine.f90#L1449-L1450

Might be a inconsistency which was fixed in `define` recently.

**Comment by fabothch** [comment]
Yes, I saw that before, but if this would be an issue, then the charge should always be dropped for Cu/Pd containing molecules. But it just happens randomly and it is different for different define versions. And I will look into this again.
